language: java
sudo: false
install: true

jdk:
  - oraclejdk12

addons:
  sonarcloud: true

stages:
  - name: build
    if: type = push
  - name: build_pull_request
    if: (type = pull_request) AND (branch = develop)

jobs:
  include:
    - stage: build
      script: ./gradlew clean build test sonarqube -DsonarLogin=$SONAR_LOGIN
    - stage: build_pull_request
      script: ./gradlew clean build test sonarqube -DsonarLogin=$SONAR_LOGIN -Dsonar.pullrequest.base=$TRAVIS_BRANCH -Dsonar.pullrequest.branch=$TRAVIS_PULL_REQUEST_BRANCH -Dsonar.pullrequest.key=$TRAVIS_PULL_REQUEST -Dsonar.pullrequest.provider=GitHub -Dsonar.pullrequest.github.repository=SpinyOwl/SpinyGUI

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
    - '$HOME/.gradle'
    - '.gradle'